name = "CRC32"
uuid = "b4567568-9dcc-467e-9b62-c342d3a501d3"
version = "1.2.0"
authors = ["Steven G. Johnson <stevenj@alum.mit.edu> and contributors"]

[deps]
libdeflate_jll = "46979653-d7f6-5232-b59e-dd310c4598de"

[compat]
julia = "1.6"
libdeflate_jll = "1.26.0"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
