name = "CRC32"
uuid = "b4567568-9dcc-467e-9b62-c342d3a501d3"
authors = ["Steven G. Johnson <stevenj@alum.mit.edu> and contributors"]
version = "1.0.1"

[deps]
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"

[compat]
julia = "1.3"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
